### ISSUE TITLE
Missing axios module

### ISSUE THREAD

**Issue by rahelFain** [massimocandela/geofeed-finder#21]
Compiled geofeed-finder executable in release 1.6.0 for Linux returns the following error message:

```./geofeed-finder-linux-x64 -h
pkg/prelude/bootstrap.js:1876
      throw error;
      ^

Error: Cannot find module '/snapshot/geofeed-finder/node_modules/axios/dist/node/axios.cjs'
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at createEsmNotFoundErr (internal/modules/cjs/loader.js:929:15)
    at finalizeEsmResolution (internal/modules/cjs/loader.js:922:15)
    at resolveExports (internal/modules/cjs/loader.js:450:14)
    at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1955:46)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at Module.require (pkg/prelude/bootstrap.js:1855:31)
    at require (internal/modules/cjs/helpers.js:101:18) {
  code: 'MODULE_NOT_FOUND',
  path: '/snapshot/geofeed-finder/node_modules/axios/package.json',
  pkg: true
}
```

**Comment by massimocandela** [comment]
Hi @rahelFain,

Thanks for reporting this. It took more time than expected to fix this, it was related to 2 dependencies (used also by another nested dependency). It is fixed in v1.6.1
